packages:
  - "packages/*"
  - "examples/*"

linkWorkspacePackages: true
saveWorkspaceProtocol: false
preferWorkspacePackages: true

overrides:
  "@mirage-x/core": "workspace:*"
  "@mirage-x/virtual-object": "workspace:*"
  "@mirage-x/mirror": "workspace:*"

allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - "@frdt/binding-darwin-arm64@0.2.4"
  - "@frdt/binding-linux-x64-gnu@0.2.4"
  - "@frdt/binding-linux-x64-musl@0.2.4"
  - "@frdt/binding-win32-x64-msvc@0.2.4"
  - "@frdt/frdt@0.2.4"
