import type { Document } from "@frdt/frdt";

import { requireChild, requireReference, stringOf, variableIndex } from "../frdt/util.js";
import {
  extractPart,
  readStagedFeedback,
  readStagedMeta,
  writePart,
} from "./staging.js";

export type AttachFeedbackPaths = {
  /** Directory holding the fetched feedback (`ResFeedbackOriginal.brson`). */
  inputPath: string;
  /** Directory to write `ResFeedback.brson` / `ResFeedbackMeta.json` to. */
  outputPath: string;
};

/** The slot the root's `Static.AppRoot` points at. */
const appRootOf = (doc: Document) =>
  doc.slotById(requireReference(doc.root(), "Static.AppRoot"));

/**
 * The core: the `Main` slot under `Static.AppRoot`, with its root being
 * AppRoot, and without the environment (`Main/DV/ENV`) and the units
 * (children of `Main/Package`), which are generated by the build.
 */
export const attachCore = (option: AttachFeedbackPaths): void => {
  const doc = readStagedFeedback(option.inputPath);
  const appRoot = appRootOf(doc);
  const main = requireChild(appRoot, "Main");

  for (const child of appRoot.children()) {
    if (child.id() !== main.id()) doc.removeSlot(child);
  }
  doc.removeSlot(requireChild(requireChild(main, "DV"), "ENV"));
  for (const child of requireChild(main, "Package").children()) {
    doc.removeSlot(child);
  }

  writePart({
    outputDir: option.outputPath,
    part: extractPart(doc, appRoot),
    meta: readStagedMeta(option.inputPath),
    label: "core",
  });
};

/**
 * A frame: the whole feedback without the core (`AppRoot/Main`) and the
 * environment (`DV/ENV`). Skipped with a warning when the feedback is a
 * different frame (`Static.FrameCode`).
 */
const attachFrame = (
  option: AttachFeedbackPaths & {
    expectedFrameCode: string;
    label: string;
  },
): void => {
  const doc = readStagedFeedback(option.inputPath);
  const root = doc.root();

  const frameCodeIndex = variableIndex(root, "Static.FrameCode");
  const frameCode =
    frameCodeIndex < 0
      ? null
      : stringOf(root.tryComponentValue(frameCodeIndex, "Value"));
  if (!frameCode) {
    throw new Error("Static.FrameCode not found");
  }
  if (frameCode !== option.expectedFrameCode) {
    console.warn(
      `FrameCode is not ${option.expectedFrameCode}. FrameCode: ${frameCode}`,
    );
    return;
  }

  doc.removeSlot(requireChild(appRootOf(doc), "Main"));
  doc.removeSlot(requireChild(requireChild(root, "DV"), "ENV"));

  writePart({
    outputDir: option.outputPath,
    part: extractPart(doc, root),
    meta: readStagedMeta(option.inputPath),
    label: option.label,
  });
};

export const attachSimpleFrame = (option: AttachFeedbackPaths): void => {
  attachFrame({
    ...option,
    expectedFrameCode: "Simple",
    label: "simple frame",
  });
};

export const attachInstallFrame = (option: AttachFeedbackPaths): void => {
  attachFrame({
    ...option,
    expectedFrameCode: "InstalledAvatar",
    label: "install frame",
  });
};
